language: go
env:
  global:
  - GIT_DEPLOY_DIR=build
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="Travis CI"
  - GIT_DEPLOY_EMAIL=richard@mindginative.com
  - secure: 1L3vgun6QKckwmOxekVAML3xbjIWvyAmd0lc56e/fwZ6g0g+w3dPBZ/3hLRIE582J5uz9Vop6iMGs/MivCgWvffAt0JV/UXOjCIPXlLv3KsTBbeLzfZkSTvQ8ZuO/z1exuA3+GMz/EC462cfO9cyKtayMPDBFAPxyFaQOT4/Q1LT00ZQoV7Qk1b84eD2mts6HOmPWiOt60aVc1gfQcefnPANUJXl6IEXOLPHTMYz9JxgXe5Ksea2vp3B/VgND8ugYACM1qvJCZiojKKKzFZINPFeV86Vxpo9ZTPd8lo3cimAaNpCHlqRyVoJ0BRG6q6KTlqxAROhDVF3goABREVua/XSgPOSUEH096uluhgrmOCj4E3qheVNIOSxaXuBVPzlKohVbV1zPcbrMOKUn10lBTogPC4OP+z8z7Z7PZ4+GMxf4Y7v3FW2IjEvZMTM+/XQTUDK78fUeCYmj5qDx1ZuX5f5kTCyXbSOgsgGrKNZYokpap33kO3foIcZI6AFrrI7NU9jAoEZirVFdWaJHEagIqhV18voW2OC3JrizWCO6TOpKGTkZf93RbDZPR8RWBE309yIUX9c+tezyYwI+YIDOTwwJQ4vV69aDGAc/gdAnLu2thVY+6RDQIgvigLyXmGuinfPCBcUOmZcurkIPaa9aX1Sc3Ax2wy3SZeL+fI4Iro=
branches:
  only:
  - cms
install: go get -v github.com/spf13/hugo
script:
  - git log
  - rm -frv build
  - git clone $GIT_DEPLOY_REPO --branch master --depth 1 build && hugo
after_success:
  - cp .travis.yml build
  - cd build && git status && git add . && git commit -am '...' && cd ../
  - bash deploy.sh
