baseurl = "http://www.mindginative.com/"
languageCode = "en-us"
title = "Richard Sentino | coffee | web | dev | opensource | rants | and then some"
theme = "pickles"
disqusShortname = "mindginative"
copyright = "&copy; Copyright notice"

# build directory
publishDir = "build"

# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-55684248-1"

# Define how many posts should appear on a site
paginate = 10

	description = "xxx"
[params]
	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Richard Sentino"
	description = "coffee | web | dev | opensource | rants | and then some"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

  # social
  npm = "mindginative"
  twitter = "mindginative"
  github = "rixrix"
  linkedin = "sentino"
  contact = false
  author = ""
  bio = ""
  subtitle = "coffee | web | dev | opensource | rants | and then some"
  disqus = "mindginative"

  # custom params for strata theme
	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "me.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "♥ Opensource | Building web stuff | JavaScript/NodeJS | WebOps "
		# The icons will be shown if you enter your username
		twitter = "mindginative"
		github = "rixrix"

		copyright = [
			"&copy; Richard Sentino",
			"Design: [HTML5 UP](//html5up.net)",
			"Background Image: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.portfolio]
		hide  = true
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."



# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 1

[[menu.main]]
	name = "Projects"
	url  = "/projects/list"
	weight = 9

[[menu.main]]
	name = "About"
	url  = "/about/me"
	weight = 10
