baseurl = "http://read.mindginative.com/"
languageCode = "en-us"
title = "Richard Sentino | coffee | web | dev | opensource | rants | and then some"
theme = "sam"
disqusShortname = "mindginative"
copyright = "&copy; Copyright notice"

# buid dir and github pages
publishDir = "public"

# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-55684248-1"

# Define how many posts should appear on a site
paginate = 10
description = "xxx"

[params]
	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Richard Sentino"
	description = "coffee | web | dev | opensource | rants | and then some"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

  # social
  npm = "mindginative"
  twitter = "mindginative"
  github = "rixrix"
  linkedin = "sentino"
  contact = false
  author = ""
  bio = ""
  subtitle = "coffee | web | dev | opensource | rants | and then some"
  disqus = "mindginative"

# Sam Theme

  favicon             = "sam.ico"
  homepage            = "home"                        # What to call the home page link
  galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
  clickablePhotos     = false                          # Allow links to the full size images
  smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                        # Note: This will only become active if clickablePhotos is also true.
  smallImagesSubfolder = false                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                        # For each image the small version has to have the same filename as the big version.
  footerText          = "coffee | web | dev | opensource | rants | and then some"

  # Metadata
  twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
  primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/post"
    text = "writings"

[[params.mainMenu]]
    link = "/projects/list"
    text = "projects"

[[params.mainMenu]]
    link = "/about/me"
    text = "who dis?"
